version: '3.8'

services:
  backend:
    image: ecommerceordersystemapp:0.0.1
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_R2DBC_URL: ${SPRING_R2DBC_URL}
      SPRING_R2DBC_USERNAME: ${SPRING_R2DBC_USERNAME}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/app/sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: ["bash", "/docker-entrypoint-initdb.d/init-db.sh"]

volumes:
  postgres_data: