version: '3.8'

services:
  backend:
    image: ecommerceordersystemapp:1.0.0
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    environment:
      SPRING_R2DBC_URL: r2dbc:pool:postgresql://db:5432/ecommerce_db
      SPRING_R2DBC_USERNAME: ${SPRING_R2DBC_USERNAME}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      - mongo

  db:
    image: postgres:13
    env_file:
      - .env.example
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4
    env_file:
      - .env.example
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: orders_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: